### ISSUE TITLE
Namespace not created

### ISSUE THREAD

**Issue by rainfallsevensamurai** [DanielG/dxld-mullvad#2]
Followed readme, until init script:

```
xx@DietPi:/mnt/dietpi_userdata/dxld-mullvad-master# ./mullvad-wg-netns.sh init deb_del mullvad-bg4.conf
Invalid netns name ""
Cannot open network namespace "deb_del": No such file or directory
Error: Attribute failed policy validation.
```

Do you have a suggestion @DanielG ? Thank you!!

**Comment by DanielG** [comment]
I'm unfamilliar with this "Attribute failed policy validation" error. Could you run the script through `sh -x ./mullvad-wg-netns.sh ...` that should make it obvious what's failing.

**Comment by rainfallsevensamurai** [comment]
Thanks for your quick reply.

Result: 
```
xxx@DietPi:/mnt/dietpi_userdata/dxld-mullvad-master# sh -x ./mullvad-wg-netns.sh init deb_del mullvad-bg4.conf
+ set -e
+ cmd=init
+ shift
+ init deb_del mullvad-bg4.conf
+ nsname=deb_del
+ shift
+ cfgname=mullvad-bg4.conf
+ shift
+ parentns=
+ wgifname=wg-deb_del
+ [ -z  ]
+ set --
+ [ -z  ]
+ [ -e /sys/class/net/wg-deb_del ]
+ ip netns exec  [ -e /sys/class/net/wg-deb_del ]
Invalid netns name ""
+ ip netns exec deb_del [ -e /sys/class/net/wg-deb_del ]
Cannot open network namespace "deb_del": No such file or directory
+ ip link add wg-deb_del type wireguard
Error: Attribute failed policy validation.
```

Maybe looks like it's using the username as mullvad config name?

**Comment by DanielG** [comment]
On my system that command works without issue. Perhaps this is due to some AppArmour/SELinux policy active on your system that restricts interface names? Can you try using an interface name without an underscore?

Also check MAC policy, one of:

    $ aa-enabled

or 

    $ sestatus

If neigher of those exist that's probably not it either and we'll have to dig deeper.

**Comment by rainfallsevensamurai** [comment]
We've made some progress!

```
root@DietPi:/mnt/dietpi_userdata/dxld-mullvad-master# sestatus
-bash: sestatus: command not found
root@DietPi:/mnt/dietpi_userdata/dxld-mullvad-master# aa-enabled
-bash: aa-enabled: command not found
```

I'm running DietPi, which creates a user for Deluge, called debian_deluged  (I edited the name in the previous code fragments). It appears like that name is too long for an interface name, because when I try:

```
root@DietPi:/mnt/dietpi_userdata/dxld-mullvad-master# sh -x ./mullvad-wg-netns.sh init debian_de mullvad-bg4.conf
+ set -e
+ cmd=init
+ shift
+ init debian_de mullvad-bg4.conf
+ nsname=debian_de
+ shift
+ cfgname=mullvad-bg4.conf
+ shift
+ parentns=
+ wgifname=wg-debian_de
+ [ -z  ]
+ set --
+ [ -z  ]
+ [ -e /sys/class/net/wg-debian_de ]
+ ip netns exec  [ -e /sys/class/net/wg-debian_de ]
Invalid netns name ""
+ ip netns exec debian_de [ -e /sys/class/net/wg-debian_de ]
Cannot open network namespace "debian_de": No such file or directory
+ ip link add wg-debian_de type wireguard
+ [ -e /var/run/netns/debian_de ]
+ ip netns add debian_de
+ ip link set wg-debian_de netns debian_de
+ cat /etc/wireguard/mullvad-bg4.conf
+ grep -vi ^Address\|^DNS
+ ip netns exec debian_de wg setconf wg-debian_de /dev/stdin
+ sed -rn s/^Address *= *([0-9a-fA-F:/.,]+) *$/\1/ip
+ addrs=10.65.71.238/32,fc00:bbbb:bbbb:bb01::2:47ed/128
+ ip -netns debian_de link set dev lo up
+ ip -netns debian_de link set dev wg-debian_de up
+ IFS=,
+ ip -netns debian_de addr add dev wg-debian_de 10.65.71.238/32
+ ip -netns debian_de addr add dev wg-debian_de fc00:bbbb:bbbb:bb01::2:47ed/128
+ ip -netns debian_de route add default dev wg-debian_de
+ ip -netns debian_de -6 route add default dev wg-debian_de
```

However there are still errors. Also, I would like to use the default username if possible.

**Comment by DanielG** [comment]
The remaining errors are just part of cleanup commands nothing to worry about.

Unfortunately the interface size limit really is a hard-limit. So hard it has a fixed C define (IFNAMSIZ) that can only be changed by recompiling your entire distribution :D I wonder if the netns name has a similar restrictive size limit? https://github.com/JonathanCasey/mullvad-ubuntu/issues/3 and the associated patch seems to suggest not.

Fundamentally I would argue if what you want is to stick individual services into a namespace my tooling just isn't a good fit. My use case is more oriented towards actual (human) login users that might also run services via custom systemd system or user services (the latter being untested but should work).

Importantly in that use-case the username is something I can pick to be appropriate as an interface name.

If you want to try running deluged as a systemd user unit I could help with testing just have to dig out my deluged.service file and adapt it a bit.

**Comment by rainfallsevensamurai** [comment]
Ah ok, thanks!

I've changed the username to something shorter, and changed the deluged en web .conf files to use that name. The services are started and running good. I also redid the steps in de readme file and ran the init command again, using the new, shorter, username.

However, it doesn't seem to work? I suppose I'm missing a step or two. How can I check if this is working at all? I tried:

```
sudo -u deluge curl https://am.i.mullvad.net/connected
curl: (6) Could not resolve host: am.i.mullvad.net
```

ifconfig doesn't show any new tunnels.

**Comment by rainfallsevensamurai** [comment]
Output of init -x

```
sh -x ./mullvad-wg-netns.sh init deluge mullvad-bg4.conf
+ set -e
+ cmd=init
+ shift
+ init deluge mullvad-bg4.conf
+ nsname=deluge
+ shift
+ cfgname=mullvad-bg4.conf
+ shift
+ parentns=
+ wgifname=wg-deluge
+ [ -z  ]
+ set --
+ [ -z  ]
+ [ -e /sys/class/net/wg-deluge ]
+ ip netns exec  [ -e /sys/class/net/wg-deluge ]
Invalid netns name ""
+ ip netns exec deluge [ -e /sys/class/net/wg-deluge ]
+ ip -netns deluge link del dev wg-deluge
+ ip link add wg-deluge type wireguard
+ [ -e /var/run/netns/deluge ]
+ ip link set wg-deluge netns deluge
+ cat /etc/wireguard/mullvad-bg4.conf
+ grep -vi ^Address\|^DNS
+ ip netns exec deluge wg setconf wg-deluge /dev/stdin
+ sed -rn s/^Address *= *([0-9a-fA-F:/.,]+) *$/\1/ip
+ addrs=10.65.71.238/32,fc00:bbbb:bbbb:bb01::2:47ed/128
+ ip -netns deluge link set dev lo up
+ ip -netns deluge link set dev wg-deluge up
+ IFS=,
+ ip -netns deluge addr add dev wg-deluge 10.65.71.238/32
+ ip -netns deluge addr add dev wg-deluge fc00:bbbb:bbbb:bb01::2:47ed/128
+ ip -netns deluge route add default dev wg-deluge
+ ip -netns deluge -6 route add default dev wg-deluge
```

**Comment by DanielG** [comment]
Hmm try `ip -netns deluge addr` to make sure it's not a sudo specific PAM problem.

You did the `pam-auth-update --enable libpam-net-usernet`, right? That should result in:

```
$ grep -r usernet /etc/pam.d/                                                                                                                                                      ~ 
/etc/pam.d/common-session:session	optional	pam_usernet.so 
/etc/pam.d/common-session-noninteractive:session	optional	pam_usernet.so
```

**Comment by rainfallsevensamurai** [comment]
Sorry for the delay. 

I had to do a reboot as well, but here is the output:

```
root@DietPi:~# ip -netns deluge addr
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever
30: wg-deluge: <POINTOPOINT,NOARP,UP,LOWER_UP> mtu 1420 qdisc noqueue state UNKNOWN group default qlen 1000
    link/none
    inet xxx/32 scope global wg-deluge
       valid_lft forever preferred_lft forever
    inet6 xxxx:xxxx:xxxx:bb01::2:47ed/128 scope global
       valid_lft forever preferred_lft forever
root@DietPi:~# curl https://am.i.mullvad.net/connected
You are connected to Mullvad (server bg4-wireguard). Your IP address is xxx
root@DietPi:~#
```

This looks like the tunnel is active for all users and processes. Am I wrong in thinking this was meant to be a way to activate the tunnel just for user deluge?

```
root@DietPi:~# grep -r usernet /etc/pam.d/
/etc/pam.d/common-session:session       optional        pam_usernet.so
/etc/pam.d/common-session-noninteractive:session        optional        pam_usernet.so
root@DietPi:~#
```

**Comment by DanielG** [comment]
Ok, so the tunnel does get initialized properly in the deluge netns. What we still have to figure out then is whether processes launced as user `deluge` get moved into the right netns. `sudo -u deluge ip addr` should show the same as `ip -netns deluge addr` in that case.

If so the problem is likely the DNS/resolv configuration. The way that works is ip-netns overrides /etc/resolv.conf by mounting /etc/netns/<netns name>/resolv.conf over it when the netns is created. You should check that file points at the mullvad nameserver as documented in the readme when running in a `sudo -u deluge` context but at your usual nameserver when on the main system. 

> This looks like the tunnel is active for all users and processes.

I'm not sure what you mean?

**Comment by rainfallsevensamurai** [comment]
Ok, `sudo -u deluge ip addr` and `ip -netns deluge addr` show exactly the same information.

I've did follow the readme and already created a folder deluge in /etc/netns/ with a resolv.conf file, pointing to Mullvad. There are no other folders in /etc/netns/ for other users, so I don't know how I would have to configure this part: 

> but at your usual nameserver when on the main system

What I mean with "the tunnel is active for all users and processes" is: At the moment it looks like every process and application is trying to use the tunnel, because I get all kinds of dns resolve errors (pihole can't update, radarr can't get results, etc). If I run `ip addr` as root I get a mullvad-xxx connection, which I find strange, because I don't want root (or any other user, except deluge) to use this vpn tunnel.

Thank you for all your help, I'm new to all this and maybe I'm trying to accomplish something that is not really possible.

**Comment by DanielG** [comment]
I think we just need a quick sync chat session to figure this out: https://web.libera.chat/?nick=rainfallsevensamurai?#dxld-mullvad if you have time.

**Comment by rainfallsevensamurai** [comment]
Thanks again for the chat session, Daniel.
